# Generated by Django 4.0.4 on 2022-04-29 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Задание')),
                ('text', models.TextField(verbose_name='Суть задания')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('level', models.FloatField(default=0.5, verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
